- name: install and start nginx
  hosts: 10.0.0.0
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started