- name: varibles from task level
  hosts: mongodb
  vars:
    NAME: raja
    JOB: DevOps
  tasks:
  - name: printing variables from play level
    ansible.builtin.debug:
      msg: "my name is {{NAME}}, Job is {{JOB}}" 
  - name: variables from task level
    vars:
      NAME: Kumara
      JOB: Cloud
    ansible.builtin.debug:
      msg: "my name is {{NAME}}, Job is {{JOB}}"
