- name: creating user
  hosts: localhost
  tasks:
  - name: check user is exist
    ansible.builtin.command: id Chinna
    register: output
    ignore_errors: true
  - name: creating user
    become: yes
    ansible.builtin.user:
      name: Chinna
    when: output.rc != 0