- name: using loops
  hosts: localhost
  tasks:
  - name: printing name using loops
    ansible.builtin.debug:
      msg: "hello {{item}}"
    loop:
      - raja
      - pooja
  - name: love
    ansible.builtin.debug:
      msg: "{{item}} loves {{item}}"