- name: map of list
  hosts: localhost
  tasks:
  - name: install and uninstall packages
    ansible.builtin.yum:
      name: {{item.name}}
      state: {{item.state}}
    loop:
      - {name: 'nginx', state: 'installed'}
      - {name: 'postfix', state: 'absent'}