- name: deploying catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: nodejs env
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed

  - name: check roboshop user exist or not
    ansible.builtin.stat:
      path: /home/roboshop
    register: output

  - name: printing output
    ansible.builtin.debug:
      msg: "{{output}}"

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
    when: output.stat.exists == false

  - name: directory exist
    ansible.builtin.stat:
      path: /app
    register: output1

  - name: creating directory
    ansible.builtin.command: mkdir /app
    when: output1.stat.exists == false

  - name: downloading Zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: unziping
    ansible.builtin.unarchive:
       src: /tmp/catalogue.zip
       dest: /app
       remote_src: yes

  # - name: download new files and unzip
  #   ansible.builtin.shell:
  #     cmd: |
  #       curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
  #       cd /app && unzip /tmp/catalogue.zip

  - name: install dependencies
    ansible.builtin.shell:
      cmd: |
        cd /app
        npm install 

  - name: catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: demon reload
    ansible.builtin.systemd:
      daemon_reload: true
      name: catalogue
      state: started
      enabled: yes
  
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongo shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading scama
    ansible.builtin.command: mongo --host 172.31.29.72 </app/schema/catalogue.js

  - name: restart catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
 
